### ISSUE TITLE
Unable to run weekly call

### ISSUE THREAD

**Issue by brentirwin** [brentirwin/sfs-emailer#4]
$ python3 run.py -w
July 22 09:22
Traceback (most recent call last):
  File "run.py", line 66, in <module>
    email(freq, args.sample, args.test)
  File "/root/sfs-emailer/src/emailer.py", line 20, in email
    data = get_call(frequency, sample)
  File "/root/sfs-emailer/src/rota.py", line 166, in get_call
    return weekly_call(rota)
  File "/root/sfs-emailer/src/rota.py", line 136, in weekly_call
    date = datetime.datetime.strptime(get_date(rota[row][0]), '%A, %B %d')
  File "/root/sfs-emailer/src/rota.py", line 39, in get_date
    date = datetime.datetime.strptime(date, '%d %B %Y')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '1 Augu 2019' does not match format '%d %B %Y'

**Comment by brentirwin** [comment]
Oh! It's made to pull "st" out of the string for 1st, 21st, or 31st. So it's pulling it off the end of August as well. I need to make an exception so that it doesn't do that for the word August.
